# Generated by Django 4.2.2 on 2025-08-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_product_ciengramos_remove_product_dccgramos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measurement',
        ),
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('we', 'Weight'), ('un', 'Unit')], default='we', max_length=2),
        ),
    ]
