# Generated by Django 4.2.2 on 2025-08-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_measurement_product_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure',
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('bo', 'Both'), ('un', 'Unit')], default='kg', max_length=2),
        ),
    ]
