"""
Django settings for condimentos project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-xz7)%@bu9(ez1qs^j^_#&7yo(1ahg1gkgb4&%#_71$^#-3^p*y')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'api.casacondimentos.com',  # Subdominio para el backend y admin
    'casacondimentos.com',
    'www.casacondimentos.com',
    '127.0.0.1:8000',
    '127.0.0.1',
    'localhost',  # Para desarrollo local
    'localhost:8000',  # Para desarrollo local con puerto
]

CSRF_TRUSTED_ORIGINS = [
    'https://api.casacondimentos.com',  # Subdominio para el backend y admin
    'https://casacondimentos.com',
    'https://www.casacondimentos.com',
    'http://localhost:8000',  # Para desarrollo local
    'http://127.0.0.1:8000',  # Para desarrollo local
]

# Configuración de CSRF y Sesiones (se sobrescribe abajo según DEBUG)
CSRF_COOKIE_SECURE = True  # Solo se envía CSRF en HTTPS



# Application definition

INSTALLED_APPS = [

    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir primero
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise para archivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',  # Sesiones antes de CSRF
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración de Sesiones
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'condimentos_session'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 días

# Configuración de cookies para desarrollo
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
    SESSION_COOKIE_SECURE = False  # False para desarrollo (HTTP)
    SESSION_COOKIE_SAMESITE = 'Lax'  # Lax permite navegación y fetch same-site
    CSRF_COOKIE_SECURE = False  # False para desarrollo (HTTP)
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_HTTPONLY = False  # False para permitir acceso desde JavaScript
    SESSION_COOKIE_DOMAIN = None  # None para desarrollo local
    # Configuración adicional para desarrollo
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:5173',
        'http://127.0.0.1:5173',
    ])
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOW_CREDENTIALS = True
    SESSION_COOKIE_SECURE = True  # True para producción (HTTPS)
    SESSION_COOKIE_SAMESITE = 'Strict'
    CSRF_COOKIE_SECURE = True  # True para producción (HTTPS)
    CSRF_COOKIE_SAMESITE = 'Strict'
    SESSION_COOKIE_HTTPONLY = True

SESSION_COOKIE_DOMAIN = None  # None para permitir subdominios

# Configuración de CORS para React (se sobrescribe arriba según DEBUG)
# CORS_ALLOW_CREDENTIALS = True  # Comentado porque se maneja arriba
# CORS_ORIGIN_ALLOW_ALL = True  # Comentado porque se maneja arriba

# Configurar orígenes permitidos para React
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",  # React development server (alternativo)
    "http://localhost:5173",  # Vite development server
    "http://127.0.0.1:5173",  # Vite development server (alternativo)
    "http://127.0.0.1:8000",  # Django development server
    "http://localhost:8000",  # Django development server (alternativo)
]

# Configuración adicional para CORS y sesiones
CORS_EXPOSE_HEADERS = ['Set-Cookie']
CORS_ALLOW_CREDENTIALS = True

# Headers permitidos para CORS
CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cookie',  # Agregar cookie header
]

# Métodos HTTP permitidos para CORS
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

APPEND_SLASH = False

ROOT_URLCONF = 'condimentos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'condimentos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Usar directorio de volumen si existe (Docker), sino usar BASE_DIR (local)
DB_DIR = Path('/app/data') if Path('/app/data').exists() else BASE_DIR

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Directorio para archivos estáticos recopilados

MEDIA_URL = '/images/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')

STATICFILES_DIRS = [
    # Configuración para archivos estáticos de DRF
]

# Configuración de WhiteNoise para servir archivos estáticos
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
if DEBUG:
    # Configuración para desarrollo - solo JSON para evitar problemas con CORS
    REST_FRAMEWORK = {
        'DEFAULT_RENDERER_CLASSES': [
            'rest_framework.renderers.JSONRenderer',          # Solo JSON
        ],
        'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
        'PAGE_SIZE': 20,  # 20 productos por página
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework.authentication.SessionAuthentication',
        ],
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny',
        ],
    }
else:
    # Configuración para producción - solo JSON
    REST_FRAMEWORK = {
        'DEFAULT_RENDERER_CLASSES': [
            'rest_framework.renderers.JSONRenderer',
        ],
        'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
        'PAGE_SIZE': 20,  # 20 productos por página
        'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework.authentication.SessionAuthentication',
        ],
        'DEFAULT_PERMISSION_CLASSES': [
            'rest_framework.permissions.AllowAny',
        ],
    }
